chore: upgrade dependencies (#1153)
* chore(backend): upgrade redis from 3.0.2 to 3.1.2

* chore(frontend): upgrade react-draft-wysiwyg from 1.14.5 to 1.14.6

* chore(frontend): upgrade validator from 13.0.0 to 13.6.0

* chore(templating): upgrade @types/cheerio from 0.22.24 to 0.22.28

* chore(templating): upgrade @types/node from 14.14.31 to 14.14.42

* chore: upgrade twilio from 3.55.1 to 3.58.0

* chore(verify-backup): upgrade @types/express to v4.17.11

* chore(backend): upgrade @types/express to v4.17.11

* chore: update package-lock

This forces @types/serve-static to update to fix a build error:

node_modules/@types/express/index.d.ts(58,29): error TS2694: Namespace 'serveStatic' has no exported member 'RequestHandlerConstructor'.

* fix(backend): fix type errors regarding request query params

Errors:

src/core/middlewares/campaign.middleware.ts(109,7): error TS2322: Type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
src/core/middlewares/campaign.middleware.ts(110,7): error TS2322: Type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
src/core/middlewares/upload.middleware.ts(21,7): error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/core/middlewares/upload.middleware.ts(56,7): error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

* chore(backend): revert @types/express upgrade

We might need to upgrade celebrate to fix the type definitions for this.
Look into that later.

This reverts commits 73bbb3f1665ccbe11a97b27514c75e5413fabc37,
cec757ae4692f91061d9a886bc1cba95d6d31c18, and 858c4b86390b69f348b8ca7686afbf4b821d5df6.

* fix(backend): upgrade moment from 2.24.0 to 2.29.1

Snyk has created this PR to upgrade moment from 2.24.0 to 2.29.1.

See this package in npm:
https://www.npmjs.com/package/moment

See this project in Snyk:
https://app.snyk.io/org/open-government-products/project/6dc7b18b-fc34-4e3d-89f8-13b286a0abce?utm_source=github&utm_medium=upgrade-pr

* fix: upgrade @types/papaparse from 5.0.3 to 5.2.5

Snyk has created this PR to upgrade @types/papaparse from 5.0.3 to 5.2.5.

See this package in npm:
https://www.npmjs.com/package/@types/papaparse

See this project in Snyk:
https://app.snyk.io/org/open-government-products/project/6dc7b18b-fc34-4e3d-89f8-13b286a0abce?utm_source=github&utm_medium=upgrade-pr

* fix(frontend): fix build error due to @types/papaparse upgrade

Error:
/home/travis/build/opengovsg/postmangovsg/frontend/src/services/telegram.service.ts
TypeScript error in /home/travis/build/opengovsg/postmangovsg/frontend/src/services/telegram.service.ts(149,15):
Object is possibly 'undefined'.  TS2532
    147 |             delimiter === ',' &&
    148 |               // papaparse parses everything, including images, pdfs... This checks that at least one of the columns is sane
  > 149 |               fields.some((field) => /^[a-zA-Z0-9\s-_'"/]+$/.test(field))
        |               ^
    150 |           )
    151 |         },
    152 |         error: function () {

The change that caused it:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d54d34007a3d55ef9a611b81a07b1da6693bdcf1

* fix(frontend): fix another error due to @types/papaparse upgrade

* chore(backend): upgrade @types/papaparse from v5.0.3 to v5.2.5

Also fix the following build error:
src/core/services/parse-csv.service.ts:55:15 - error TS2532: Object is possibly 'undefined'.

55               meta.fields?.length > 0 &&
                 ~~~~~~~~~~~~~~~~~~~

Fix this by changing `meta.fields?.length > 0` to `meta.fields?.length`
since this would check for non-undefinedness and a non-zero number at
the same time.

Co-authored-by: Zhao Wei Liew <zhaoweiliew@gmail.com>
Co-authored-by: snyk-bot <snyk-bot@snyk.io>