chore(backend): upgrade @types/papaparse from v5.0.3 to v5.2.5
Also fix the following build error:
src/core/services/parse-csv.service.ts:55:15 - error TS2532: Object is possibly 'undefined'.

55               meta.fields?.length > 0 &&
                 ~~~~~~~~~~~~~~~~~~~

Fix this by changing `meta.fields?.length > 0` to `meta.fields?.length`
since this would check for non-undefinedness and a non-zero number at
the same time.